### PR TITLE
Fix recursive copy when using --as-dockerfile on non scm-managed folder

### LINKED ISSUE #937: Recursive copy when using --as-dockerfile on non scm-managed folder
Trying to generate a `Dockerfile` on a non-scm-manage folder (aka no `.git` or `.hg`, …) fails when preparing the context folder (aka `upload`). 
It copies the folder to `upload` but doesn't ignore `upload` itself and thus end up doing a never-ending copy (until the filesystem complains).

```bash
$ ls /tmp/foo/
config.py  README.md  requirements.txt  wsgi.py
$ pwd
/tmp/foo
/t/bar λ s2i build --as-dockerfile=Dockerfile /tmp/foo centos/python-36-centos7 vdemeester/helloworld-python
Build failed
ERROR: An error occurred: open /tmp/foo/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src/upload/src: too many open files
$ rm -fR *
$ s2i --loglevel=5 build --as-dockerfile=Dockerfile /tmp/bar centos/python-36-centos7 vdemeester/helloworld-python
I1022 17:00:27.703272   28796 build.go:50] Running S2I version "unknown"
I1022 17:00:27.703691   28796 util.go:58] Getting docker credentials for centos/python-36-centos7
I1022 17:00:27.703762   28796 util.go:74] Using  credentials for pulling centos/python-36-centos7
I1022 17:00:27.703889   28796 build.go:163]
Source:                         /tmp/foo
Output Image Tag:               vdemeester/helloworld-python
Environment:
Labels:
Incremental Build:              disabled
Remove Old Build:               disabled
Builder Pull Policy:            if-not-present
Previous Image Pull Policy:     if-not-present
Quiet:                          disabled
Layered Build:                  disabled
Docker Endpoint:                unix:///var/run/docker.sock
Docker Pull Config:             /home/vincent/.docker/config.json
Docker Pull User:               vdemeester

I1022 17:00:27.704144   28796 install.go:261] Using "assemble" installed from "image:///usr/libexec/s2i/assemble"
I1022 17:00:27.704206   28796 install.go:261] Using "run" installed from "image:///usr/libexec/s2i/run"
I1022 17:00:27.704237   28796 install.go:261] Using "save-artifacts" installed from "image:///usr/libexec/s2i/save-artifacts"
I1022 17:00:27.704259   28796 scm.go:20] DownloadForSource /tmp/bar
I1022 17:00:27.704316   28796 download.go:38] Copying sources from "/tmp/bar" to "upload/src"
I1022 17:00:27.704474   28796 fs.go:247] D "/tmp/foo/downloads" -> "upload/src/downloads"
I1022 17:00:27.704663   28796 fs.go:247] D "/tmp/foo/downloads/scripts" -> "upload/src/downloads/scripts"
I1022 17:00:27.704828   28796 fs.go:247] D "/tmp/foo/downloads/defaultScripts" -> "upload/src/downloads/defaultScripts"
I1022 17:00:27.704963   28796 fs.go:247] D "/tmp/foo/upload" -> "upload/src/upload"
I1022 17:00:27.705095   28796 fs.go:247] D "/tmp/foo/upload/src" -> "upload/src/upload/src"
I1022 17:00:27.705199   28796 fs.go:247] D "/tmp/foo/upload/src/upload" -> "upload/src/upload/src/upload"
# […]
```

/kind bug

### PR DESCRIPTION
**Pull request by vdemeester**
Adds the possibility to ignore files/folder before copying content.

Fixes #937 

- [ ] need a non regression-test

/cc @bparees 

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

### CODE REVIEW

File: pkg/scm/downloaders/file/download.go [hunk 1]
```diff
@@ -39,8 +39,20 @@ func (f *File) Download(config *api.Config) (*git.SourceInfo, error) {
...
+
+	ignoreFiles := []string{}
+	absDst, err := filepath.Abs(config.WorkingSourceDir)
+	if err != nil {
+		return nil, err
+	}
+	if filepath.HasPrefix(absDst, copySrc) {
+		dir, _ := filepath.Split(config.WorkingSourceDir)
+		ignoreFiles = append(ignoreFiles, filepath.Clean(dir))
+	}
```
Comment (bparees) [inline pkg/scm/downloaders/file/download.go]: we were attempting to handle this more bluntly on lines 39-41.  But obviously we missed converting the paths to absolute before comparing them.  I somewhat prefer fixing that logic though, and just considering this usage invalid (ie you always need to target a different directory for your output/Dockerfile)

Comment (vdemeester) [reply pkg/scm/downloaders/file/download.go]: @bparees Oh right, how did I miss that… 

> considering this usage invalid (ie you always need to target a different directory for your output/Dockerfile)

I'm not sure why it should be invalid though ? or more accurately, I think in this case the error should "help" the user (telling it to specify another *output* directory).

Anyway, I'll update the conditions in lines 39-41 :wink:

Comment (bparees) [reply pkg/scm/downloaders/file/download.go]: it doesn't have to be invalid, your approach could definitely work, i just find it simpler to reason about the idea that we should always create a clean destination directory rather than polluting the working directory which could just confuse the user.

**Comment by bparees** [comment]
[merge]

File: pkg/scm/downloaders/file/download.go (hunk 1 above)
Comment (vdemeester) [reply pkg/scm/downloaders/file/download.go]: @bparees agreed :angel: :wink: :wine_glass:
